### ISSUE TITLE
مرا بخوان

### ISSUE THREAD

**Issue by ParsaHY** [mdanialh/parsinal#3]
خود گیت اینو به عنوان مرا بخوان در نظر نمیگیره تو صفحه اول ریپو. سنگین تر نیست اسمشو برگردونیم؟

**Comment by mohsenkamini** [comment]
در [71f7650](https://github.com/mdanialh/parsinal/commit/71f76501ac3d780dc45611dfa00f72e6a400dbfb) برگرداندم تا چاره‌ای بیاندیشیم.
