### ISSUE TITLE
درخواست تغییر در قسمت توضیحات پروژه

### ISSUE THREAD

**Issue by mohsenkamini** [mdanialh/parsinal#6]
لطفا در قسمت توضیحات هم پارسی را پاس بداریم.
![image](https://github.com/mdanialh/parsinal/assets/77579794/e67eba5d-56d6-40ec-8622-3ef24423fec5)

**Comment by mdanialh** [comment]
انجام شد :)

**Comment by mohsenkamini** [comment]
خدا خیرت بده.
